postgres://hppoc:password@127.0.0.1:5432/fabricexplorer

Property config.syncStartDate set to  2018/01/01


Please open web browser to access ï¼šhttp://localhost:8080/


pid is 20823


Insert sql is INSERT INTO orderer  ( "requests","server_hostname" ) VALUES( $1,$2  ) RETURNING *;
INSERT ID: 1
Insert sql is INSERT INTO chaincodes  ( "name","version","path","channel_genesis_hash" ) VALUES( $1,$2,$3,$4  ) RETURNING *;
Insert sql is INSERT INTO peer  ( "requests","channel_genesis_hash","server_hostname" ) VALUES( $1,$2,$3  ) RETURNING *;
INSERT ID: 10
INSERT ID: 1
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
Insert sql is INSERT INTO channel  ( "name","createdt","blocks","trans","channel_hash","channel_genesis_hash" ) VALUES( $1,$2,$3,$4,$5,$6  ) RETURNING *;
INSERT ID: 1
INSERT ID: 3
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 6
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 2
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 7
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 3
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 8
Successfully received the block event[object Object]
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 4
Broadcast >> {"title":"Block 3 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 3 established with 1 tx","time":"2018-09-16T15:38:11.000Z","txcount":1,"datahash":"e2c07cc70b8030d0732a94eb880befe9f262aa0d0ed5fd20793a83a2a68754c1"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 9
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 5
Broadcast >> {"title":"Block 4 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 4 established with 1 tx","time":"2018-09-16T15:38:15.000Z","txcount":1,"datahash":"b31f5dd191a56bdaa54b01c5783bbebb6440868cd86f39a9d4259361eacd841c"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 10
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 6
Broadcast >> {"title":"Block 5 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 5 established with 3 tx","time":"2018-09-16T15:38:31.000Z","txcount":3,"datahash":"81c6a3ae2a8770106b72b41661d317297f3ccd9fc45ee1c9a6a1fc4c26d744ee"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 11
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 12
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 13
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 7
Broadcast >> {"title":"Block 6 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 6 established with 1 tx","time":"2018-09-16T15:39:17.000Z","txcount":1,"datahash":"0566601a2f04cb0e75d1b91868a1cf1ef271ffab2300da4ae5918a20822168ec"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 14
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 8
Broadcast >> {"title":"Block 7 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 7 established with 1 tx","time":"2018-09-16T15:39:29.000Z","txcount":1,"datahash":"30019650b1e39f67d8706a39bb0688a333d43cfd746026a3b03f068d573d833a"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 15
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20823) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 9
Broadcast >> {"title":"Block 8 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 8 established with 1 tx","time":"2018-09-16T16:04:21.000Z","txcount":1,"datahash":"88b398f0925a2532999a4f0a4c9c763bf7b7e05c6ccbbacdfd6514fff38998a2"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 16
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 10
Broadcast >> {"title":"Block 9 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 9 established with 1 tx","time":"2018-09-16T16:05:00.000Z","txcount":1,"datahash":"02db50c834b91ca50da3ab331a1fd2278987ac5b264fd04f5cd2abcf36c4b1d9"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 17
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
Failed to receive the block event ::Error: 14 UNAVAILABLE: EOF
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:20823) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:20823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
Received kill signal, shutting down gracefully
Closed out remaining connections
postgres://hppoc:password@127.0.0.1:5432/fabricexplorer

Property config.syncStartDate set to  2018/01/01


Please open web browser to access ï¼šhttp://localhost:8080/


pid is 31958


Insert sql is INSERT INTO peer  ( "requests","channel_genesis_hash","server_hostname" ) VALUES( $1,$2,$3  ) RETURNING *;
INSERT ID: 2
Insert sql is INSERT INTO chaincodes  ( "name","version","path","channel_genesis_hash" ) VALUES( $1,$2,$3,$4  ) RETURNING *;
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
Insert sql is INSERT INTO channel  ( "name","createdt","blocks","trans","channel_hash","channel_genesis_hash" ) VALUES( $1,$2,$3,$4,$5,$6  ) RETURNING *;
INSERT ID: 11
INSERT ID: 11
INSERT ID: 4
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 18
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 12
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 19
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 13
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 20
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 14
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 21
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 15
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 22
Successfully received the block event[object Object]
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 16
Broadcast >> {"title":"Block 5 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 5 established with 1 tx","time":"2018-09-16T16:23:07.000Z","txcount":1,"datahash":"15e59de2227d5d842c6dbe29004257d1dac619ee82bc99d8953714adf7d53712"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 23
Successfully received the block event[object Object]
Insert sql is INSERT INTO blocks  ( "blocknum","prehash","datahash","blockhash","txcount","channel_genesis_hash","createdt" ) VALUES( $1,$2,$3,$4,$5,$6,$7  ) RETURNING *;
INSERT ID: 17
Broadcast >> {"title":"Block 6 added to: mychannel","channelName":"mychannel","type":"block","message":"Block 6 established with 1 tx","time":"2018-09-16T16:23:42.000Z","txcount":1,"datahash":"133f5701efa373e4e2154684708a8c96122ec5bdb13ab60d633d04c0f211ae86"}
Insert sql is INSERT INTO transactions  ( "blockid","txhash","createdt","chaincodename","chaincode_id","status","creator_msp_id","endorser_msp_id","tx_response","type","read_set","write_set","channel_genesis_hash","validation_code","envelope_signature","payload_extension","creator_nonce","chaincode_proposal_input","endorser_signature","creator_id_bytes","payload_proposal_hash","endorser_id_bytes" ) VALUES( $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22  ) RETURNING *;
INSERT ID: 24
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31958) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
Failed to receive the block event ::Error: 14 UNAVAILABLE: EOF
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
[31merror[39m: [Admin.js]: GetStatus - timed out after:45000
(node:31958) UnhandledPromiseRejectionWarning: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/home/rashid/Documents/blockchain-explorer-0.3.5/app/platform/fabric/Admin.js:125:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
